### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by tomviering** [michaelchughes/KMeansRex#1]
As in the readme stated, I first compiled libkmeansrex.so using their suggested command, this worked. Then I get stuck when executing: 
mex KMeansRex.cpp ./libkmeansrex.so -I Eigen 
I've put the header files of the Eigen Matrix Template Library in the folder Eigen. 

I get the error: LINK : fatal error LNK1561: entry point must be defined

I'm using Windows 8 and the compiler: Microsoft Software Development Kit (SDK) 7.1 in C:\Program Files (x86)\Microsoft Visual Studio 10.0, and Matlab version 2011b.

**Comment by michaelchughes** [comment]
I've never tested this on Windows and I don't have access to a Windows machine at the moment, so I may not be able to totally solve this. However,
- what compiler did you use? I suspect that if you'll need to use a version of gcc/g++ to get this working properly. http://www.mingw.org/
- you could also attempt to try the python version with your current .so file... if this works, then the error is related to matlab's mex and its interactions with the .so file
- sometimes Visual Studio can work with mex, but it might need some special handling: http://coachk.cs.ucf.edu/GPGPU/Compiling_a_MEX_file_with_Visual_Studio2.htm 

Hope that helps.  Good luck, and let me know if you still have problems.

**Comment by michaelchughes** [comment]
RESOLVED.
