### ISSUE TITLE
Code Optimizations 0001

### ISSUE THREAD

**Issue by RoyiAvital** [michaelchughes/KMeansRex#8]
Hello,

Got some code optimizations for this program:

- I'd offer a version which supports Single Precision. It's really easy to do by changing:
```
typedef Map<ArrayXXd> ExtMat;
typedef ArrayXXd Mat;
typedef ArrayXd Vec;
```
Into:
```
typedef Map<ArrayXXf> ExtMat;
typedef ArrayXXf Mat;
typedef ArrayXf Vec;
```
And use `float *` instead of `double *`.

- At the function `pairwise_distance` in order to accelerate the [calculation of the distance](https://github.com/michaelchughes/KMeansRex/blob/master/src/KMeansRexCore.cpp#L154) one should change `Dist = -2*(X.matrix() * Mu.transpose().matrix());` into `Dist.noalias() = -2*(X.matrix() * Mu.transpose().matrix());`.

- At the function `sampleRowsPlusPlus` there are few issues:
    - No need for the variable `Vec ChosenIDs`.
    - The first Index Selection should be from a Uniform Vector of size N not K (This is a bug).
    - The Probabilities Weights vector of the [K-Means++](https://en.wikipedia.org/wiki/K-means%2B%2B) should be generated from the Squared Distance, not the Distance itself. Hence `curDist = (X.rowwise() - Mu.row(kk-1)).square().rowwise().sum().sqrt();` becomes `curDist = (X.rowwise() - Mu.row(kk-1)).square().rowwise().sum();`.

Thank You.

**Comment by michaelchughes** [comment]
Thanks! I've just pushed fixes to the two bugs you mentioned:

* first choice should be one-of-N not one-of-K
* not using sqrt

As you can probably tell, this is an old library not very actively maintained. I'm not able to spend time on the other optimizations, but if you want to create a reasonable PR I'm happy to consider them.

**Comment by RoyiAvital** [comment]
Hi,

To tell you the truth, I have no idea how to create PR.

Moreover, I use Windows and Visual Studio hence things aren't as easy as it should.
